### ISSUE TITLE
Enhancements in README.md

### ISSUE THREAD

**Issue by dkeriazisStuy** [NathanielUnger/dazed-and-amazed#1]
> # English or pseudocode description of algorithm
> if the next closest adjacent square is the treasure return true else if there are no open paths (dead end) remove until the last square where there are at least 2 forks in path else if there is only square that is legal to move onto move forward else move one block forward in the most leftward adjacent direction, where the path has never travelled before

I believe that this could be further enhanced, namely in three ways:
1. Instead of looking at the "next closest adjacent square" for treasure, it might be simpler to check if the _current_ square is a treasure, and return `true` accordingly
2. Similarly, instead of checking for open paths, you can just check if the current square is a wall, and backtrack if that is the case
3. Instead of checking specifically "if there is only [one] square that is legal to move onto", you can just attempt moving onto all the adjacent squares and recurse, with the assurance that the above two cases will check for legality

> # base case
> return the boolean value of the statement "the maze is navigable, having a legal travel path that is one unit long and that is continuous from a start point to an existing treasure"

The base case would have to be altered to reflect the changes made above, as well.

**Comment by zhanglydia** [comment]
In addition to what Daniel said, the recursive abstraction uses the words "start point" and in class we address how that can be confusing.

**Comment by NathanielUnger** [comment]
Thank you for your help!

**Comment by kevinzhao4939** [comment]
Thank you for your help!
